### ISSUE TITLE
Making an Attraction-Repulsion Package in ROS

### ISSUE THREAD

**Issue by proffessorx** [MartinWieczorek/paparazzi#11]
Making an Attraction-Repulsion Package in ROS

**Comment by proffessorx** [comment]
Downloaded bag files and tested its data on rqt graph and rqt plot.

**Comment by MartinWieczorek** [comment]
next steps:
 - [x] feed the bag-data into the Camera-Tracking ImageProcessing-Node
 - [x] create a Attraction-Repulsion-Node in ROS that uses position-data to calculate forces

**Comment by Ali6074** [comment]
Next Step:
[ ] display Attraction-Repulsion on Rviz
