### ISSUE TITLE
Attraction Repulsion Inputs

### ISSUE THREAD

**Issue by steup** [MartinWieczorek/paparazzi#6]
* Camera Tracking as global  Position Input -> Needs to be transmit to the copter
* Reformulate Attraction Repulsion to Distances -> Fixed Orientation of Distances, Missing Identy Information

**Comment by proffessorx** [comment]
"Camera Tracking"
> If Swarm Cohesion (supposedly our 2nd Major milestone) requires Camera tracking(CT), then it makes more sense to use C.T.
> Also, CT, as we know till now, will give much accurate results. (Advantages)
> Possibly slower frequency, learning ROS, and communication with the GND station seems to be challenges till now (disadvantages/Challenges)
By, Ali, Vivek, Martin

**Comment by proffessorx** [comment]
"Using Sonars and reformulating A-R functions"

[Main Challenge:- Does one Copter's Sonar effect the other Copter's Sonar?]

>'Whole-Area Sensing':
we discussed and found few problems with 'Whole-Area Sensing' technique to distinguish copters.
   -Small changes in Yaw will change the whole environment (disadv)
   -Good for global positioning. (adv).
   -Connection between copters needs to be established  (Challenge)

> 'Distinguishing from sonars'
1.One way is to use 2 consecutive sensors for walls and one sensor for Copter.
 -Very rough
2.Second way is distiguishing through controlling the Trasmitter of Sonar Sensor of one copter to obtain sonar from other copter.
 -Possible? (chalenge) 
3.Third way is distinguishing through the fluctuation from Sonar Readings. As copters fluctuates Sonar reading more and Wall's readings are comparitively more solid and steady
-Very rough
By, Ali, Vivek, Martin

**Comment by proffessorx** [comment]
For Camera Tracking:
(establishing connection with GND station and making node)
http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28c%2B%2B%29
http://wiki.ros.org/ROS/Tutorials

**Comment by vivek87799** [comment]
The positions from the camera are being sent via ivy.
Attraction and repulsion node calculates the force of att/rep.
